// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy_sRP_4QJFxd_gMCV5uySkKs2_wh-Sfw',
    appId: '1:811249833341:web:9ff596115364e2498c2814',
    messagingSenderId: '811249833341',
    projectId: 'medapp-890ff',
    authDomain: 'medapp-890ff.firebaseapp.com',
    databaseURL: 'https://medapp-890ff-default-rtdb.firebaseio.com',
    storageBucket: 'medapp-890ff.appspot.com',
    measurementId: 'G-L2XYS81EX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsFvhKC1cXcF8hargCLK1hSs2iV6ugoTI',
    appId: '1:811249833341:android:7edc099f2a29f47c8c2814',
    messagingSenderId: '811249833341',
    projectId: 'medapp-890ff',
    databaseURL: 'https://medapp-890ff-default-rtdb.firebaseio.com',
    storageBucket: 'medapp-890ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0p02elhIcHUWObfmoILNU8m0ZHa9O7l0',
    appId: '1:811249833341:ios:cf6d3ba45de1819c8c2814',
    messagingSenderId: '811249833341',
    projectId: 'medapp-890ff',
    databaseURL: 'https://medapp-890ff-default-rtdb.firebaseio.com',
    storageBucket: 'medapp-890ff.appspot.com',
    iosClientId: '811249833341-16g9bdkane1v4rj1rnt5sb7li2jgbg6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0p02elhIcHUWObfmoILNU8m0ZHa9O7l0',
    appId: '1:811249833341:ios:cf6d3ba45de1819c8c2814',
    messagingSenderId: '811249833341',
    projectId: 'medapp-890ff',
    databaseURL: 'https://medapp-890ff-default-rtdb.firebaseio.com',
    storageBucket: 'medapp-890ff.appspot.com',
    iosClientId: '811249833341-16g9bdkane1v4rj1rnt5sb7li2jgbg6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc',
  );
}
